# Generated by Django 5.1.7 on 2025-03-26 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("doctor_management_api", "0001_initial"),
        (
            "patient_doctor_api",
            "0002_remove_patient_user_delete_medicalrecord_and_more",
        ),
        ("patient_management_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientDoctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patients",
                        to="doctor_management_api.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_doctors",
                        to="patient_management_api.patient",
                    ),
                ),
            ],
        ),
    ]
